steps:
  - label: "Trigger step with plugins"
    plugins:
      - github.com/buildkite-plugins/foo#bar: ~
    trigger: "trigger-another-pipeline"
    # skip: true
    # notify:
    #   - github_commit_status:
    #       context: "my-custom-status"
