env:
  URL3: "localhost:9000"

steps:
  - label: ":construction_worker: Build"
    command: echo "Build the rocket" && buildkite-agent annotate 'Annotate Example `default` style' --context 'ctx-default'
    key: build

  - label: ":white_check_mark: Test"
    command: echo "Test the rocket with env var ${ENV_NUM:-1234}"
    key: test
    depends_on: build

  - label: ":rocket: Deploy"
    command: echo "Launch the rocket"
    key: deploy
    depends_on: test
